manager/urls.py
from django.urls import path
from manager import views
from manager.views import delete_worker_from_team, create_tag, delete_tag

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("accounts/login/",
         views.UserLoginView.as_view(), name="login"),
    path("accounts/logout/",
         views.UserLogoutView.as_view(), name="logout"),
    path("workers/",
         views.WorkerListView.as_view(), name="worker-list"),
    path("wokers/<int:pk>/",
         views.WorkerDetailView.as_view(), name="worker-detail"),
    path("profile/",
         views.ProfileDetailView.as_view(), name="current-profile"),
    path("workers/create/",
         views.WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/",
         views.WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/",
         views.WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/",
         views.TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/toggle_assignment/",
         views.toggle_task_assignment, name="task-toggle-assignment"),
    path("tasks/<int:pk>/toggle_completed/",
         views.toggle_task_completed, name="task-toggle-completed"),
    path("task/<int:pk>/",
         views.TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/update/",
         views.TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/",
         views.TaskDeleteView.as_view(), name="task-delete"),
    path("task/create/",
         views.TaskCreateView.as_view(), name="task-create"),
    path("projects/",
         views.ProjectListView.as_view(), name="project-list"),
    path("project/<int:pk>/",
         views.ProjectDetailView.as_view(), name="project-detail"),
    path("project/team/<int:pk>/",
         views.toggle_project_by_team, name="project-team-toggle"),
    path("project/<int:pk>/delete/",
         views.ProjectDeleteView.as_view(), name="project-delete"),
    path("project/<int:pk>/update/",
         views.ProjectUpdateView.as_view(), name="project-update"),
    path("project/create/",
         views.ProjectCreateView.as_view(), name="project-create"),
    path("teams/<int:pk>/",
         views.TeamDetailView.as_view(), name="team-detail"),
    path("add_worker/", views.add_worker_to_team, name="add-worker"),
    path("teams/create/", views.TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/",
         views.TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete_worker/<int:user_pk>/",
         delete_worker_from_team, name="team-delete-worker"),
    path("teams/<int:pk>/delete/",
         views.TeamDeleteView.as_view(), name="team-delete"),
    path("create_tag/", create_tag, name="create-tag"),
    path("delete_tag/", delete_tag, name="delete-tag"),
]

app_name = "manager"

simplify-tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager"), name="manager"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

manager/models.py
import os
import uuid
from datetime import timedelta
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone


phone_number_validator = RegexValidator(
    regex=r'^\+?1?\d{9,15}$',
    message="Phone number must be entered in the format: '+999999999'",
)


def unique_file_path(instance: callable, filename: str) -> str:
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join("profile_pictures/", filename)


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"


class Worker(AbstractUser):
    profile_picture = models.ImageField(
        upload_to=unique_file_path,
        default="profile_pictures/default.jpg",
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        related_name="workers",
        blank=True,
        null=True,
    )
    description = models.TextField(blank=True)
    phone_number = models.CharField(
        max_length=15,
        validators=[phone_number_validator],
        blank=True,
        null=True,
    )
    last_activity = models.DateField(default=timezone.now)
    is_online = models.BooleanField(default=False)
    instagram = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    twitter = models.URLField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    team = models.ForeignKey(
        "Team",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="workers"
    )

    class Meta:
        ordering = ("position", "username")

    def __str__(self):
        return f"{self.username}"

    def check_is_online(self, days: int = 1) -> bool:
        status = (timezone.now().date()
                  - self.last_activity < timedelta(days=days))
        self.is_online = status
        self.save()
        return status

    def reset_picture(self) -> None:
        if self.profile_picture.name != self.profile_picture.field.default:
            self.profile_picture.delete(save=False)
        self.profile_picture = self.profile_picture.field.default
        self.save()


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"


class Team(models.Model):
    name = models.CharField(max_length=255)
    leader = models.ForeignKey(
        "Worker",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="leader_of"
    )

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    team = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        null=True,
        related_name="projects"
    )

    def __str__(self):
        return f"{self.name}, (Team: {self.team})"


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    choices = [
        (1, "Lowest"),
        (2, "Low"),
        (3, "Medium"),
        (4, "High"),
        (5, "Highest"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.IntegerField(choices=choices, default=3)
    task_type = models.ForeignKey(
        TaskType, on_delete=models.CASCADE, related_name="tasks"
    )
    assigners = models.ManyToManyField(Worker, related_name="tasks")
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="tasks",
        blank=True,
        null=True
    )
    tags = models.ManyToManyField(Tag, related_name="tasks")
    completed_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ("deadline", "priority", "name")

    def __str__(self):
        return f"{self.name}"

manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.templatetags.static import static
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet, Q
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpRequest, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    TemplateView,
    DeleteView
)

from manager.forms import (
    LoginForm,
    WorkerSearchForm,
    WorkerForm,
    TaskSearchForm,
    TaskForm,
    TeamForm,
    ProjectForm
)
from manager.models import (
    Worker,
    Task,
    Project,
    Team, Tag
)


class UserLoginView(LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy("manager:index"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        remember_me = self.request.POST.get("rememberMe", False)
        if remember_me:
            self.request.session.set_expiry(3600 * 24 * 7)
        else:
            self.request.session.set_expiry(0)

        return response


class UserLogoutView(LogoutView):
    template_name = "accounts/logged_out.html"


class IndexView(TemplateView):
    template_name = "manager/index.html"

    def get_context_data(self, **kwargs):
        tasks_completed = round(Task.objects.filter(
            is_completed=True
        ).count() / Task.objects.count() * 100)
        tasks_not_completed = round(
            Task.objects.filter(is_completed=False).count()
            / Task.objects.count() * 100)
        month = timezone.now().month
        tasks_this_month = Task.objects.filter(
            is_completed=True,
            completed_at__month=month).count()
        context = super().get_context_data(**kwargs)
        context["tasks"] = Task.objects.filter(
            is_completed=True
        ).order_by("-completed_at")[:6]
        context["workers_count"] = Worker.objects.count()
        context["tasks_count"] = Task.objects.count()
        context["tasks_completed"] = tasks_completed
        context["tasks_not_completed"] = tasks_not_completed
        context["tasks_completed_rounded"] = round(tasks_completed / 10) * 10
        context["tasks_not_completed_rounded"] = round(
            tasks_not_completed / 10) * 10
        context["tasks_this_month"] = tasks_this_month
        context["projects_count"] = Project.objects.count()
        context["teams_count"] = Team.objects.count()
        context["segment"] = "home page"
        return context


class WorkerListView(ListView):
    model = Worker
    context_object_name = "workers"
    template_name = "manager/worker_list.html"
    paginate_by = 10

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "workers"
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Worker.objects.all()
        username = self.request.GET.get("username")
        status = self.request.GET.get("status")
        if username:
            queryset = queryset.filter(username__icontains=username)
        if status:
            if status == "Online":
                queryset = queryset.filter(is_online=True)
            elif status == "Offline":
                queryset = queryset.filter(is_online=False)
        return queryset


class WorkerDetailView(DetailView):
    model = Worker
    context_object_name = "worker"
    template_name = "manager/profile.html"
    queryset = Worker.objects.all()

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "profile"
        return context

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        user = get_object_or_404(Worker, pk=pk)
        if request.user.is_authenticated and request.user == user:
            return HttpResponseRedirect(reverse("manager:current-profile"))
        return super().get(request, *args, **kwargs)


class WorkerCreateView(LoginRequiredMixin, CreateView):
    model = Worker
    form_class = WorkerForm
    template_name = "manager/worker_form.html"

    def get_success_url(self):
        return reverse_lazy("manager:worker-detail", args=[self.object.pk])

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "create worker"
        context["picture"] = static("/default.jpg")
        return context


class WorkerUpdateView(LoginRequiredMixin, UpdateView):
    model = Worker
    template_name = "manager/worker_form.html"
    form_class = WorkerForm

    def get_success_url(self):
        return reverse_lazy("manager:worker-detail", args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = f"worker #{self.object.pk} edit"
        context["picture"] = get_object_or_404(
            Worker,
            pk=self.object.pk).profile_picture.url
        return context


class ProfileDetailView(LoginRequiredMixin, TemplateView):
    template_name = "manager/profile.html"
    queryset = Worker.objects.all().select_related("team")

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "profile"
        try:
            context["worker"] = Worker.objects.get(pk=self.request.user.pk)
        except Worker.DoesNotExist:
            raise Http404("Profile does not exist")
        return context


class WorkerDeleteView(LoginRequiredMixin, DeleteView):
    model = get_user_model()
    template_name = "manager/confirm_delete.html"

    def get_success_url(self):
        return reverse_lazy("manager:worker-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = "worker delete"
        context["model"] = "worker"
        return context


class TaskListView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "manager/task_list.html"
    paginate_by = 8

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "tasks"
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        context["tags"] = Tag.objects.all()
        return context

    def get_queryset(self) -> QuerySet:
        name = self.request.GET.get("name")
        user = self.request.GET.get("user")
        task_filter = self.request.GET.get("filter")
        tag = self.request.GET.get("tag")
        if task_filter == "all":
            queryset = Task.objects.all().filter(project=None)
        elif task_filter == "available":
            queryset = Task.objects.all().filter(Q(project=None) & ~Q(assigners__in=[self.request.user]))
        elif user:
            queryset = Task.objects.filter(project=None, assigners__in=[user])
        else:
            queryset = Task.objects.all().filter(
                project=None,
                is_completed=False
            )
        if name:
            queryset = queryset.filter(name__icontains=name)
        if tag:
            queryset = queryset.filter(tags__name__icontains=tag)
        return queryset.order_by("is_completed", "-completed_at")


class TaskDetailView(DetailView):
    model = Task
    context_object_name = "task"
    template_name = "manager/task_detail.html"

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["segment"] = "task"
        project = self.request.GET.get("project")
        if project:
            context["project"] = Project.objects.get(pk=project)
        return context

    def get_queryset(self) -> QuerySet:
        queryset = Task.objects.all().select_related("project")
        queryset = queryset.prefetch_related("assigners")
        return queryset


@login_required
def toggle_task_assignment(
        request: HttpRequest,
        pk: int) -> HttpResponseRedirect:
    user = request.user
    task = get_object_or_404(Task, pk=pk)
    if user in task.assigners.all():
        task.assigners.remove(user)
    else:
        if task.project:
            if task.project.team and user in task.project.team.workers:
                task.assigners.add(user)
        else:
            task.assigners.add(user)
    task.save()
    return HttpResponseRedirect(reverse_lazy("manager:task-list"))


@login_required
def toggle_task_completed(
        request: HttpRequest,
        pk: int) -> HttpResponseRedirect:
    user = request.user
    task = get_object_or_404(Task, pk=pk)
    if user in task.assigners.all() or user.is_superuser:
        if task.is_completed:
            task.is_completed = False
            task.completed_at = None
        else:
            task.is_completed = True
            task.completed_at = timezone.now()
    task.save()
    project = request.GET.get("project", None)
    if project:

templates/manager/index.html
{% extends "layouts/base.html" %}
{% load static %}


{% block content %}

  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-6 col-12">
        <div class="row">

          <div class="col-lg-6 col-md-6 col-12">
            <div class="card">
              <span class="mask bg-primary opacity-10 border-radius-lg"></span>
              <div class="card-body p-3 position-relative">
                <div class="row">
                  <div class="col-8 text-start">
                    <div class="icon icon-shape bg-white shadow text-center border-radius-2xl">
                      <a href="{% url "manager:worker-list" %}">
                        <i class="ni ni-circle-08 text-dark text-gradient text-lg opacity-10 icon-link"
                           aria-hidden="true"></i>
                      </a>
                    </div>
                    <h5 class="text-white font-weight-bolder mb-0 mt-3">
                      {{ workers_count }}
                    </h5>
                    <span class="text-white text-sm">Employee Active</span>
                  </div>
                  <div class="col-4">
                    <div class="dropstart text-end mb-6">
                      <a href="javascript:;" class="cursor-pointer" id="dropdownUsers1" data-bs-toggle="dropdown"
                         aria-expanded="false">
                        <i class="fa fa-ellipsis-h text-white"></i>
                      </a>
                      <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownUsers1">
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item border-radius-md" href="{% url "manager:worker-create" %}">Create</a></li>
                        {% endif %}
                      <li><a class="dropdown-item border-radius-md" href="{% url "manager:worker-list" %}">Show all</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-12 mt-4 mt-md-0">
            <div class="card">
              <span class="mask bg-dark opacity-10 border-radius-lg"></span>
              <div class="card-body p-3 position-relative">
                <div class="row">
                  <div class="col-8 text-start">
                    <div class="icon icon-shape bg-white shadow text-center border-radius-2xl">
                      <a href="{% url "manager:task-list" %}">
                        <i class="ni ni-bullet-list-67 text-dark text-gradient text-lg opacity-10 icon-link"
                           aria-hidden="true"></i>
                      </a>
                    </div>
                    <h5 class="text-white font-weight-bolder mb-0 mt-3">
                      {{ tasks_count }}
                    </h5>
                    <span class="text-white text-sm">Tasks</span>
                  </div>
                  <div class="col-4">
                    <div class="dropstart text-end mb-6">
                      <a href="javascript:;" class="cursor-pointer" id="dropdownUsers2" data-bs-toggle="dropdown"
                         aria-expanded="false">
                        <i class="fa fa-ellipsis-h text-white"></i>
                      </a>
                      <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownUsers2">
                        <li><a class="dropdown-item border-radius-md" href="{% url "manager:task-list" %}">Show all</a></li>
                        {% if user.is_superuser %}
                          <li><a class="dropdown-item border-radius-md" href="{% url "manager:task-create" %}">Create</a></li>
                        {% endif %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row mt-4">
          <div class="col-lg-6 col-md-6 col-12">
            <div class="card">
              <span class="mask bg-dark opacity-10 border-radius-lg"></span>
              <div class="card-body p-3 position-relative">
                <div class="row">
                  <div class="col-8 text-start">
                    <div class="icon icon-shape bg-white shadow text-center border-radius-2xl">
                      <a href="#">
                        <i class="ni ni-single-02 text-dark text-gradient text-lg opacity-10 icon-link" aria-hidden="true"></i>
                      </a>
                    </div>
                    <h5 class="text-white font-weight-bolder mb-0 mt-3">
                      {{ teams_count }}
                    </h5>
                    <span class="text-white text-sm">Teams</span>
                  </div>
                  <div class="col-4">
                    <div class="dropstart text-end mb-6">
                      <a href="javascript:;" class="cursor-pointer" id="dropdownUsers3" data-bs-toggle="dropdown"
                         aria-expanded="false">
                        <i class="fa fa-ellipsis-h text-white"></i>
                      </a>
                      <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownUsers3">
                        {% if user.team %}
                          <li><a class="dropdown-item border-radius-md" href="{% url "manager:team-detail" pk=user.team.pk %}">Show team</a></li>
                        {% elif user.is_authenticated %}
                          <li><a class="dropdown-item border-radius-md" href="{% url "manager:team-create" %}">Create</a></li>
                        {% else %}
                          <li><span class="dropdown-item border-radius-md">No actions available</span></li>
                        {% endif %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-12 mt-4 mt-md-0">
            <div class="card">
              <span class="mask bg-primary opacity-10 border-radius-lg"></span>
              <div class="card-body p-3 position-relative">
                <div class="row">
                  <div class="col-8 text-start">
                    <div class="icon icon-shape bg-white shadow text-center border-radius-2xl">
                      <a href="{% url "manager:project-list" %}">
                        <i class="ni ni-folder-17 text-dark text-gradient text-lg opacity-10 icon-link" aria-hidden="true"></i>
                      </a>
                    </div>
                    <h5 class="text-white font-weight-bolder mb-0 mt-3">
                      {{ projects_count }}
                    </h5>
                    <span class="text-white text-sm">Projects</span>
                  </div>
                  <div class="col-4">
                    <div class="dropstart text-end mb-6">
                      <a href="javascript:;" class="cursor-pointer" id="dropdownUsers4" data-bs-toggle="dropdown"
                         aria-expanded="false">
                        <i class="fa fa-ellipsis-h text-white"></i>
                      </a>
                      <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownUsers4">
                        {% if user.is_superuser %}
                          <li><a class="dropdown-item border-radius-md" href="{% url "manager:project-create" %}">Add project</a></li>
                        {% endif %}
                        <li><a class="dropdown-item border-radius-md" href="{% url "manager:project-list" %}">Show all</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-12 mt-4 mt-lg-0">
        <div class="card shadow h-100">
          <div class="card-header pb-0 p-3">
            <h6 class="mb-0">Tasks</h6>
          </div>
          <div class="card-body pb-0 p-3 pb-2">
            <ul class="list-group">
              <li class="list-group-item border-0 d-flex align-items-center px-0">
                <div class="w-100">
                  <div class="d-flex mb-2">
                    <span class="me-2 text-sm font-weight-bold text-dark">Tasks completed</span>
                    <span class="ms-auto text-sm font-weight-bold">{{ tasks_completed }}%</span>
                  </div>
                  <div>
                    <div class="progress progress-md">
                      <div class="progress-bar bg-success w-{{ tasks_completed_rounded }}" role="progressbar"
                           aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="list-group-item border-0 d-flex align-items-center px-0">
                <div class="w-100">
                  <div class="d-flex mb-2">
                    <span class="me-2 text-sm font-weight-bold text-dark">Tasks not completed</span>
                    <span class="ms-auto text-sm font-weight-bold">{{ tasks_not_completed }}%</span>
                  </div>
                  <div>
                    <div class="progress progress-md">
                      <div class="progress-bar bg-danger w-{{ tasks_not_completed_rounded }}" role="progressbar"
                           aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <div class="card-footer pt-0 p-3 d-flex align-items-center">
            <div class="w-60">
              <p class="text-sm">
                We went through more than <b>{{ tasks_count }}</b> tasks with over than <b>{{ workers_count }}</b>
                workers.
              </p>
            </div>
            <div class="w-40 text-end">
              <a class="btn btn-dark mb-0 text-end" href="{% url "manager:task-list" %}">View all tasks</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row my-4">
      <div class="col-lg-8 col-md-6 mb-md-0 mb-4">
        <div class="card h-100">
          <div class="card-body p-3 m-2">
            <div class="row">
              <div class="col-lg-6">
                <div class="d-flex flex-column h-100">
                  <p class="mb-1 pt-2 text-bold">Join our Team</p>
                  <h5 class="font-weight-bolder">Organization</h5>
                  <p class="mb-5">From creating unique interfaces
                    to tackling complex challenges.<br>
                    Become part of a company where every step leads to success🚀</p>
                  <a class="text-body text-sm font-weight-bold mb-0 icon-move-right mt-auto"
                     href="https://mail.google.com/mail/?view=cm&to=organization@example.com"
                     target="_blank">
                    Contact us
                    <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
                  </a>
                </div>
              </div>
              <div class="col-lg-5 ms-auto text-center mt-5 mt-lg-0">
                <div class="bg-dark border-radius-lg h-100">
                  <div class="position-relative d-flex align-items-center justify-content-center h-100">
                    <img class="w-100 position-relative z-index-2 pt-4"
                         src="{% static "images/pc.png" %}" alt="pc">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 col-md-6">
        <div class="card h-100">
          <div class="card-header pb-1">
            <h6>Tasks overview</h6>
            <p class="text-sm">
              <i class="fa fa-arrow-up text-success" aria-hidden="true"></i>
              <span class="font-weight-bold">{{ tasks_this_month }}</span> tasks completed this month
            </p>
          </div>
          <div class="card-body p-3">
            <div class="timeline timeline-one-side">
              {% for task in tasks %}
                <div class="timeline-block mb-3">
              <span class="timeline-step">
                <i class="ni ni-check-bold text-success text-gradient"></i>
              </span>
                  <div class="timeline-content">
                    <h6 class="text-dark text-sm font-weight-bold mb-0">{{ task.name|truncatechars:50 }}</h6>
                    <p class="text-secondary font-weight-bold text-xs mt-1 mb-0">{{ task.completed_at }}</p>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}