manager/urls.py
from django.urls import path
from manager import views
from manager.views import delete_worker_from_team, create_tag, delete_tag

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("accounts/login/",
         views.UserLoginView.as_view(), name="login"),
    path("accounts/logout/",
         views.UserLogoutView.as_view(), name="logout"),
    path("workers/",
         views.WorkerListView.as_view(), name="worker-list"),
    path("wokers/<int:pk>/",
         views.WorkerDetailView.as_view(), name="worker-detail"),
    path("profile/",
         views.ProfileDetailView.as_view(), name="current-profile"),
    path("workers/create/",
         views.WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/",
         views.WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/",
         views.WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/",
         views.TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/toggle_assignment/",
         views.toggle_task_assignment, name="task-toggle-assignment"),
    path("tasks/<int:pk>/toggle_completed/",
         views.toggle_task_completed, name="task-toggle-completed"),
    path("task/<int:pk>/",
         views.TaskDetailView.as_view(), name="task-detail"),
    path("task/<int:pk>/update/",
         views.TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/",
         views.TaskDeleteView.as_view(), name="task-delete"),
    path("task/create/",
         views.TaskCreateView.as_view(), name="task-create"),
    path("projects/",
         views.ProjectListView.as_view(), name="project-list"),
    path("project/<int:pk>/",
         views.ProjectDetailView.as_view(), name="project-detail"),
    path("project/team/<int:pk>/",
         views.toggle_project_by_team, name="project-team-toggle"),
    path("project/<int:pk>/delete/",
         views.ProjectDeleteView.as_view(), name="project-delete"),
    path("project/<int:pk>/update/",
         views.ProjectUpdateView.as_view(), name="project-update"),
    path("project/create/",
         views.ProjectCreateView.as_view(), name="project-create"),
    path("teams/<int:pk>/",
         views.TeamDetailView.as_view(), name="team-detail"),
    path("add_worker/", views.add_worker_to_team, name="add-worker"),
    path("teams/create/", views.TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/",
         views.TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete_worker/<int:user_pk>/",
         delete_worker_from_team, name="team-delete-worker"),
    path("teams/<int:pk>/delete/",
         views.TeamDeleteView.as_view(), name="team-delete"),
    path("create_tag/", create_tag, name="create-tag"),
    path("delete_tag/", delete_tag, name="delete-tag"),
]

app_name = "manager"

simplify-tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager"), name="manager"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

templates/includes/footer.html
<footer class="footer pt-3 ml-17-5">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6 mb-lg-0 mb-4">
        <div class="copyright text-center text-sm text-muted text-lg-start">
          Portfolio Website coded by <a href="https://www.instagram.com/vivertonick/" class="font-weight-bold">Danylo
          Skepskyi</a>.
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <div class="git-hub-container">
              <a href="https://github.com/SkepskyiDanylo/it-task-manager.git" class="git-hub text-muted"><i
                class="fa-brands fa-github fs-4"></i></a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/form_errors.html
{% if form.errors %}
  <div class="error-container" id="toast-container">
    {% for field, errors in form.errors.items %}
      <div>
        {% for error in errors %}
          <div>
            <span class="text-bold text-sm text-danger mb-1">{{ field|capfirst }}: {{ error }}</span>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
    <button class="close-toast" onclick="closeToast()"><i class="fa-solid fa-x"></i></button>
  </div>
{% endif %}
<script>
    document.getElementById('profile-upload').addEventListener('change', function (event) {
        let file = event.target.files[0];
        if (file) {
            let reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById('userImage').src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    });

    function closeToast() {
        document.getElementById('toast-container').style.display = 'none';
    }
</script>

templates/includes/head.html
{% load static %}


<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="apple-touch-icon" sizes="76x76" href="{% static "images/main-logo.png" %}">
<link rel="icon" type="image/png" href="{% static "images/main-logo.png" %}">

<title>
  SimplifyTasks 
</title>


<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,800" rel="stylesheet" />
<!-- Nucleo Icons -->
<link href="https://demos.creative-tim.com/argon-dashboard-pro/assets/css/nucleo-icons.css" rel="stylesheet" />
<link href="https://demos.creative-tim.com/argon-dashboard-pro/assets/css/nucleo-svg.css" rel="stylesheet" />
<!-- Font Awesome Icons -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/js/all.min.js" crossorigin="anonymous"></script>
<!-- CSS Files -->
<link id="pagestyle" href="{% static "assets/css/soft-ui-dashboard.css" %}?v=1.1.0" rel="stylesheet" />
<link rel="stylesheet" href="{% static "css/styles.css" %}">

templates/includes/navigation.html
{% load static replace_value %}

<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
     navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
        <li class="breadcrumb-item text-sm"><a id="toggleSidenav" class="opacity-5 text-dark" href="{% url "manager:index" %}">Pages</a></li>
        <li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{ segment|replace_value:"_" }}</li>
      </ol>
      <h6 class="font-weight-bolder mb-0">{{ segment|replace_value:"_" }}</h6>
    </nav>
    <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
      <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        <ul class="navbar-nav  justify-content-end">
          <li class="nav-item d-flex align-items-center">
            {% if request.user.is_authenticated %}
              <a class="nav-link text-body font-weight-bold px-0" href="{% url "manager:current-profile" %}">
                <i class="fa-solid fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">{{ user.username|capfirst }}</span>
              </a>
            {% else %}
              <a href="{% url "manager:login" %}" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign In</span>
              </a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}

  <nav>
    <ul class="pagination mb-0">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">
            <
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="">
            <
          </a>
        </li>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == 1 and num <= 5 %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% elif page_obj.number == 2 and num <= 5 %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% elif page_obj.number == page_obj.paginator.num_pages and num >= page_obj.number|add:-4 %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% elif page_obj.number == page_obj.paginator.num_pages|add:-1 and num >= page_obj.number|add:-3 %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% elif num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?{% query_transform request page=num %}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">
            >
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link disabled" href="">
            >
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/scripts.html
{% load static %}


<!--   Core JS Files   -->
<script src="{% static "assets/js/core/popper.min.js" %}"></script>
<script src="{% static "assets/js/core/bootstrap.min.js" %}"></script>
<script>
    document.querySelectorAll('.task-card').forEach(card => {
        card.addEventListener('mousemove', (e) => {
            const rect = card.getBoundingClientRect();
            const x = (e.clientX - rect.left) / rect.width - 0.5;
            const y = (e.clientY - rect.top) / rect.height - 0.5;

            const maxRotation = 10;
            const rotateX = Math.min(Math.max(y * maxRotation, -maxRotation), maxRotation);
            const rotateY = Math.min(Math.max(x * -maxRotation, -maxRotation), maxRotation);

            card.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) scale(1.02)`;
        });

        card.addEventListener('mouseleave', () => {
            card.style.transform = 'perspective(1000px) rotateX(0deg) rotateY(0deg) scale(1)';
        });
    });
</script>

templates/includes/sidebar.html
{% load i18n static format_phone_number %}

<aside
    class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 ps bg-white"
    id="sidenav-main">
  <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
       aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href="{% url "manager:index" %}">
      <i class="fi fi-rr-home"></i>
      <img src="{% static 'images/main-logo.png' %}" class="navbar-brand-img h-100" alt="main_logo">
      <span class="ms-1 font-weight-bold">SimplifyTasks</span>
    </a>
  </div>
  <hr class="horizontal dark mt-0">
  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if segment == 'home page' %}active{% endif %}" href="{% url "manager:index" %}">
          <div
              class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
            <img src="{% static "images/home-page.png" %}" alt="home-page" class="sidebar-image">
          </div>
          <span class="nav-link-text ms-1">Home Page</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if segment == 'workers' %}active{% endif %}" href="{% url "manager:worker-list" %}">
          <div
              class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
            <img src="{% static "images/workers-page.png" %}" alt="workers-page" class="sidebar-image">
          </div>
          <span class="nav-link-text ms-1">Workers</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if segment == 'tasks' %}active{% endif %}" href="{% url "manager:task-list" %}">
          <div
              class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
            <img src="{% static "images/tasks-page.png" %}" alt="tasks-page" class="sidebar-image">
          </div>
          <span class="nav-link-text ms-1">Tasks</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if segment == 'projects' %}active{% endif %}" href="{% url 'manager:project-list' %}">
          <div
              class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
            <img src="{% static "images/projects-page.png" %}" alt="project-page" class="sidebar-image">
          </div>
          <span class="nav-link-text ms-1">Projects</span>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if segment == 'team' %}active{% endif %}" {% if request.user.team %}
             href="{% url 'manager:team-detail' pk=user.team.pk %}" {% else %} href="{% url 'manager:team-create' %}" {% endif %}>
            <div
                class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <img src="{% static "images/team.png" %}" alt="team-page" class="sidebar-image">
            </div>
            <span class="nav-link-text ms-1">Team</span>
          </a>
        </li>
      {% endif %}
      {% if request.user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="/admin/">
            <div
                class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <img src="{% static "images/admin-panel.png" %}" alt="team-page" class="sidebar-image">
            </div>
            <span class="nav-link-text ms-1">Admin panel</span>
          </a>
        </li>
      {% endif %}
      <li class="nav-item mt-3">
        <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Account pages</h6>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if segment == 'profile' %}active{% endif %}"
             href="{% url 'manager:worker-detail' pk=user.pk %}">
            <div
                class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <img src="{% static "images/profile-page.png" %}" alt="profile-page" class="sidebar-image">
            </div>
            <span class="nav-link-text ms-1">Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <form action="{% url "manager:logout" %}" method="post" class="m-0 p-0">
            {% csrf_token %}
            <button class="nav-link btn-logout" type="submit">
              <div class="icon icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                <img src="{% static "images/logout-page.png" %}" alt="logout-page" class="sidebar-image">
              </div>
              <span class="nav-link-text ms-1">Logout</span>
            </button>
          </form>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "manager:login" %}">
            <div
                class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <img src="{% static "images/login-page.png" %}" alt="login-page" class="sidebar-image">
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</aside>